apiVersion: v1
kind: Service
metadata:
  name: clashsubscribe
  labels:
    app: clashsubscribe
spec:
  ports:
    - port: 80
  selector:
    app: clashsubscribe
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clashsubscribe
spec:
  selector:
    matchLabels:
      app: clashsubscribe
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: clashsubscribe
        tier: frontend
    spec:
      containers:
        - name: clashsubscribe
          image: ccr.ccs.tencentyun.com/smiles/clashsubscribe:{TAG}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: tencent-deploy