name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Build with Maven
      run: |
        mvn -B package --file pom.xml

    - name: Docker push
      uses: azure/docker-login@v1
      with:
        login-server: ${{ vars.DOCKER_REGISTRY_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build -t ${{ vars.DOCKER_REGISTRY_SERVER }}/${{ vars.DOCKER_REGISTRY_STORAGE }}/${{ github.event.repository.name }}:${{ github.sha }} -t ${{ vars.DOCKER_REGISTRY_SERVER }}/${{ vars.DOCKER_REGISTRY_STORAGE }}/${{ github.event.repository.name }} .
        docker push ${{ vars.DOCKER_REGISTRY_SERVER }}/${{ vars.DOCKER_REGISTRY_STORAGE }}/${{ github.event.repository.name }}:${{ github.sha }}
        docker push ${{ vars.DOCKER_REGISTRY_SERVER }}/${{ vars.DOCKER_REGISTRY_STORAGE }}/${{ github.event.repository.name }}
    # 让K8s应用deployment
    - run: |
        sed -i 's/{TAG}/${{ github.sha }}/g' deployment.yaml
    - name: deploy to cluster
      uses: steebchen/kubectl@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        KUBECTL_VERSION: "v1.23.6+k3s1"
      with:
        args: apply -f deployment.yaml