name: Deploy

on:
  push:
    branches:
      - master

env:
  DOCKER_REGISTRY_SERVER: ccr.ccs.tencentyun.com
  DOCKER_REGISTRY_STORAGE: smiles
  PROJECT_NAME: clashsubscribe

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Set the Kubernetes context
        uses: azure/k8s-set-context@v2
        with:
          k8s-url: 101.33.212.124:6443
          k8s-secret: ${{ secrets.KUBE_CONFIG_DATA }}

      - name: Checkout source code
        uses: actions/checkout@v3
      - run: |
          sed -i 's/{TAG}/e518cf03a4e2691a18477964e51e62ac823298e2/g' deployment.yaml

      - name: Deploy to the Kubernetes cluster
        uses: azure/k8s-deploy@v1
        with:
          namespace: default
          manifests: |
            deployment.yaml
          images: |
            $DOCKER_REGISTRY_SERVER/$DOCKER_REGISTRY_STORAGE/$PROJECT_NAME:e518cf03a4e2691a18477964e51e62ac823298e2