name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Build with Maven
      run: |
        mvn -B package --file pom.xml

    - name: Docker push
      uses: azure/docker-login@v1
      with:
        login-server: ccr.ccs.tencentyun.com
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
      docker build -t ccr.ccs.tencentyun.com/smiles/clashsubscribe:${{ github.sha }} -t ccr.ccs.tencentyun.com/smiles/clashsubscribe .
      docker push ccr.ccs.tencentyun.com/smiles/clashsubscribe:${{ github.sha }}
      docker push ccr.ccs.tencentyun.com/smiles/clashsubscribe
